apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: k8s
spec:
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}/name/{{ .PodMeta.Name }}"
  dnsNameTemplates: 
    - "{{ .PodMeta.Namespace }}.{{ .TrustDomain }}"
---