apiVersion: v1
kind: Namespace
metadata:
  name: ennovation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ennovation-sa
  namespace: ennovation
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: ennovation
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 443
      targetPort: grpc-server
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: ennovation
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - name: https
      port: 443
      targetPort: https