apiVersion: v1
kind: Service
metadata:
  name: go-pod
  namespace: ennovation
  labels:
    app: go-pod
spec:
  selector:
    app: go-pod
  type: NodePort
  ports:
    - name: app
      port: 443
      targetPort: 8443
---
apiVersion: v1
kind: Pod
metadata:
  name: go-pod
  namespace: ennovation
  labels:
    app: go-pod
spec:
  containers:
    - name: go-pod
      image: golang:alpine
      command:
        - sleep
        - infinity
      env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
      volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets/agent.sock
          readOnly: true
        - name: src
          mountPath: /go
  volumes:
    - name: spire-agent-socket
      hostPath:
        path: /run/spire/sockets/agent.sock
        type: Socket
    - name: src
      persistentVolumeClaim:
        claimName: go-src