apiVersion: v1
kind: Pod
metadata:
  name: go-pod
  namespace: default
  labels:
    app: go-pod
spec:
  containers:
    - name: go-pod
      image: golang:alpine
      command:
        - sleep
        - infinity
      env:
        - name: TEST
          value: TEST
      volumeMounts:
        - name: src
          mountPath: /go
  volumes:
    - name: src
      persistentVolumeClaim:
        claimName: go-src